package:
  name: snap
  version: 8.0.0
  
source:
  fn:  esa-snap_sentinel_unix_8_0.sh                                                    [unix]
  url: https://download.esa.int/step/snap/8.0/installers/esa-snap_sentinel_unix_8_0.sh  [unix]
  md5: dcc44c6e305c6f299d4955a699461243                                                 [unix]

build:
  number: 2

requirements:
  host:
    - python
    - jpy
    - java-1.7.0-openjdk-cos6-x86_64=1.7.0.131
    
  run:
    - python
    - jpy
    - java-1.7.0-openjdk-cos6-x86_64=1.7.0.131

about:
  home: https://step.esa.int
  license: Apache License 2.0
  summary: Terradue packaging of the Sentinel Application Platform (SNAP)
