package:
  name: snap
  version: 9.0.0
  
source:
  fn:  esa-snap_sentinel_unix_9_0_0.sh                                                   [unix]
  url: https://download.esa.int/step/snap/9.0/installers/esa-snap_sentinel_unix_9_0_0.sh [unix]
  md5: 97b621cd4bf928ae188bfbe631dd42a5                                                  [unix]

build:
  number: 7

requirements:
  host:
    - python
    - jpy=0.9.0
    - openjdk=11.0.1
    
  run:
    - python
    - jpy=0.9.0
    - openjdk=11.0.1

about:
  home: https://step.esa.int
  license: Apache License 2.0
  summary: Terradue packaging of the Sentinel Application Platform (SNAP)
